# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


before_install:
  - export RGL_USE_NULL=TRUE

r_github_packages:
  - marionlouveaux/mgx2r  # pre-install to avoid vignette package errors

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
